### ISSUE TITLE
Calling save() deletes all hasMany relationships

### ISSUE THREAD

**Issue by oskarrough** [firebase/emberfire#142] opened 2014-10-09 18:52 UTC
If I call `this.get('model').save()`, with or without changing any properties, something removes all hasMany relationships on that model from Firebase.

I'm using ember-cli 1.1.0, emberfire 1.2.6 and ember-data 1.0.0-beta.10.

At first I thought I had a bug or wrong approach in the code below but the bug also appears when I just write save().

```JavaScript
// user-model.js
export default DS.Model.extend({
	name: DS.attr('string'),
	playlists: DS.hasMany('playlist', {async: true })
	favoritePlaylists: DS.hasMany('playlist', {async: true })
});

// playlist-model.js
export default DS.Model.extend({
	title: DS.attr('string'),
	user: DS.belongsTo('user', { inverse: 'playlists', async: true }),
	tracks: DS.hasMany('track', { async: true })
});

// newPlaylist.js
Ember.RSVP.hash({
	user: this.get('auth.user')
}).then(function(promises) {
	Ember.debug('we have the user');

	var newPlaylist = this.store.createRecord('playlist', {
		title: this.get('title'),
		user: promises.user
	});

	newPlaylist.save().then(function() {
		Ember.debug('playlist saved');
	});

	promises.user.get('playlists').then(function(userPlaylists) {
		userPlaylists.addObject(newPlaylist);
		promises.user.save().then(function() {
			Ember.debug('user saved');
		});
	});
}.bind(this));
```

**Comment by tharderer** [comment] 2015-03-10 18:29
It never works for me

**Comment by katowulf** [comment] 2015-03-10 20:14
Hey Folks. If you want to see an issue resolved, please take the time to [create an mcve](http://stackoverflow.com/help/mcve). Without a repro or additional details and conditions to narrow the scope, "me too" posts are just clutter. I'm moderating these and I'd encourage you to resubmit with useful context.

**Comment by tstirrat** [comment] 2015-04-17 18:29
@oskarrough do you still see this issue?

It is likely related the the fact that you're saving the child before you add it to the `hasMany` relationship, this means that the child was saved to the server with a `null` parent ref. If there is ever a sync from the server, this `null` can sometimes cause it to be removed from the inverse parent `hasMany` relationship.

I've found that it works best when you save in this order:

```js
var child = this.store.createRecord('child', {});
parent.get('children').addObject(child);
child.save().then(() => {
  return parent.save();
});
```

At the very least, save both objects after you've added the object to the `hasMany`.

**Comment by tstirrat** [comment] 2015-04-17 19:05
I was not able to reproduce `hasMany` relationships being cleared when replicating a project with the code you supplied.

Closing for now, Let me know if you can replicate it on `beta.16.1` and provide a MCVE.

**Closed by tstirrat** 2015-04-17 19:05 UTC
Labels: waiting for response

**Comment by oskarrough** [comment] 2015-04-17 20:14
Hey @tstirrat, thanks a lot! I'm not seeing the issue anymore and after following your pattern.

**Comment by tstirrat** [comment] 2015-04-17 20:50
Great! :balloon:
