### ISSUE TITLE
ember-data-1-0-beta-15 breaks record.serialize

### ISSUE THREAD

**Issue by h55nick** [firebase/emberfire#230] opened 2015-03-26 06:11 UTC
running almost anything through ember-fire results in
```
Uncaught TypeError: undefined is not a function.
```

the offending line here is: 
```
var serializedRecord = record.serialize({includeId:false});
```
[file/code here](https://github.com/firebase/emberfire/blob/0fcc66f60b22dbec180380b0ccf4596a720ab989/addon/adapters/firebase.js#L342)

the problem is that record is now in fact a snapshot not a record and accordingly the api has changed. 

a quick solution is: 
```
record.record.serialize({includeId: false})
```

as record.record results in the same object as the pre beta-15 api returned.

I am working on:
EmberFire - 1.4.2

Hope this helps.

notes:
http://emberjs.com/blog/2015/02/14/ember-data-1-0-beta-15-released.html

**Comment by tstirrat** [comment] 2015-03-26 17:53
Hey, thanks for the report, this looks like a dupe of #229.

I wasn't aware of `snapshot.record` to get back to the original record. We should be able to use something like `record = record.record || record` to grab the record in `beta.15`+

I'll try to find some time over the weekend to look at 15+ compat.

**Comment by tstirrat** [comment] 2015-03-26 17:54
oops I meant #226

**Closed by tstirrat** 2015-03-26 17:53 UTC

**Comment by h55nick** [comment] 2015-03-26 19:00
:+1: thanks.

**Comment by tstirrat** [comment] 2015-04-01 16:40
PR raised #234

**Comment by h55nick** [comment] 2015-04-01 21:32
Thanks!

**Comment by tstirrat** [comment] 2015-04-03 21:17
You can now upgrade emberfire to 1.4.4 in `package.json` to get this fix.
