### ISSUE TITLE
[Ember 2.0-beta.1] initializer isn't found

### ISSUE THREAD

**Issue by brianmbutler** [firebase/emberfire#264] opened 2015-06-15 16:08 UTC
Fresh install today, CLI@0.2.7 and ember canary resolution.

[Error] Error: Could not find module `emberfire/initializers/emberfire` imported from `my-app/initializers/emberfire`
	tryFinally (vendor.js, line 32)
	requireModule (vendor.js, line 148)
	global code (safetydox.js, line 2471)

**Comment by tstirrat** [comment] 2015-06-16 17:25
I cannot reproduce this, can you provide steps to reproduce?

```
ember --version
version: 0.2.7
node: 0.10.38
npm: 2.11.0


$ ember new blah
version: 0.2.7
installing
  create .bowerrc
  .. snip ..
  create vendor/.gitkeep


$ cd blah
$ ember install emberfire
version: 0.2.7
.. snip ..
Installed addon package.

$ ember serve
version: 0.2.7
..
Build successful - 3017ms.

# i updated ember to components/ember#canary in bower.json
                                                                                                                                                                                                                                                                                                         $ bower install
bower ember#canary                  install ember#02a60ab78e

ember#02a60ab78e bower_components/ember
└── jquery#1.11.3


$ ember build
version: 0.2.7
Built project successfully.
```

**Comment by brianmbutler** [comment] 2015-06-16 19:14
ember —version

version: 0.2.7
node: 0.12.4
npm: 2.11.0


$ember new my-app

$cd my-app

-Update bower.json to “ember”:”canary”.

-bower install

ember serve
Build successful - 2851ms.

Open in Chrome

Right Click - Inspect Element

Uncaught Error: Could not find module `emberfire/initializers/emberfire` imported from `my-app/initializers/emberfire`
requireFrom @ loader.js:110
reify @ loader.js:97
mod.state @ loader.js:140
tryFinally @ loader.js:21
requireModule @ loader.js:139
(anonymous function) @ ember-load-initializers.js:23
default @ ember-load-initializers.js:20
(anonymous function) @ app.js:15
mod.state @ loader.js:141
tryFinally @ loader.js:21
requireModule @ loader.js:139
(anonymous function) @ app-boot.js:25

> On Jun 16, 2015, at 1:25 PM, Tim Stirrat <notifications@github.com> wrote:
> 
> I cannot reproduce this, can you provide steps to reproduce?
> 
> ember --version
> version: 0.2.7
> node: 0.10.38
> npm: 2.11.0
> 
> 
> $ ember new blah
> version: 0.2.7
> installing
>   create .bowerrc
>   .. snip ..
>   create vendor/.gitkeep
> 
> 
> $ cd blah
> $ ember install emberfire
> version: 0.2.7
> .. snip ..
> Installed addon package.
> 
> $ ember serve
> version: 0.2.7
> ..
> Build successful - 3017ms.
> 
> # i updated ember to components/ember#canary in bower.json
>                                                                                                                                                                                                                                                                                                          $ bower install
> bower ember#canary                  install ember#02a60ab78e
> 
> ember#02a60ab78e bower_components/ember
> └── jquery#1.11.3
> 
> 
> $ ember build
> version: 0.2.7
> Built project successfully.
> —
> Reply to this email directly or view it on GitHub <https://github.com/firebase/emberfire/issues/264#issuecomment-112504752>.
>

**Comment by tstirrat** [comment] 2015-06-16 19:15
ok thanks, will take a look

**Comment by tstirrat** [comment] 2015-06-19 03:15
I havent forgotten about this issue. Seems something has changed with addon module resolving in Ember 2.0 beta and I can't see any info on what :/

**Comment by brianmbutler** [comment] 2015-06-19 03:22
Yes, I see other adding with the same issue.

**Comment by tstirrat** [comment] 2015-06-19 03:23
I thinks it's related to a number of removals:

> The ArrayPolyfills and EnumerableUtils libraries are being pulled out into a library; most apps should prefer lodash or other utility libs.

This is just one thing that's causing problems.

source: http://emberjs.com/blog/2015/05/24/another-two-oh-status-update.html

**Comment by shiv86** [comment] 2015-07-09 06:36
Hi I had exactly the same issue today. Once I removed the firebase url config from my config/environment.js file and uninstalled the npm package the error went away for emberfir BUT started occurring for the tori config described here: http://stackoverflow.com/questions/31308930/ember-cli-0-2-7-initializers-loader-uncaught-error-could-not-find-module

```javascript
module.exports = function(environment) {
  var ENV = {
    modulePrefix: 'ui',
    environment: environment,
    firebase: 'https://blistering-torch-5880.firebaseio.com/',
```

**Comment by mrkd** [comment] 2015-07-26 03:41
Is there a workaround for this issue ?

**Comment by tstirrat** [comment] 2015-07-26 15:55
I am able to get emberfire's `master` branch up and running with 2.0 canary:

```
-------------------------------
Ember      : 2.0.0-canary+6e00835b
Ember Data : 2.0.0+canary.9c83224bc0
Firebase   : 2.2.7
EmberFire  : 0.0.0
jQuery     : 1.11.3
-------------------------------
```

I used ember-cli `1.13.1`

```
ember new app
cd app
ember install firebase/emberfire#master
```

Then edit `bower.json` and set ember and ember-data to:

```js
"dependencies": {
  // ...
  "ember": "components/ember#canary",
  "ember-data": "components/ember-data#canary",
```

**Comment by leifcr** [comment] 2015-09-02 19:59
Please see PR #310, as all tests pass on Ember 2.0

**Closed** 2015-12-20 20:50 UTC
Labels: enhancement
