### ISSUE TITLE
Deprecation: add dasherized string

### ISSUE THREAD

**Issue by virgiliud** [firebase/emberfire#288] opened 2015-07-23 14:28 UTC
I'm following the Emberfire quickstart. I'm using find() to retrieve data and get the following:

```
DEPRECATION: Passing classes to store methods has been removed. Please pass a dasherized string instead of firebase-test@model:project:
        at ember$data$lib$system$store$$Service.extend.serializerFor 
```

I also get the following error:

```
Error while processing route: projects Cannot read property 'modelName' of undefined TypeError: Cannot read property 'modelName' of undefined
    at ember$data$lib$system$store$$Service.extend.adapterFor (http://localhost:4200/assets/vendor.js:81475:35)
    at ember$data$lib$system$store$$Service.extend.serializerFor (http://localhost:4200/assets/vendor.js:81518:46)
    at listenForChanges (http://localhost:4200/assets/vendor.js:98102:30)
    at recordWasPushed (http://localhost:4200/assets/vendor.js:98076:14)
    at push (http://localhost:4200/assets/vendor.js:98627:23)
    at superWrapper [as push] (http://localhost:4200/assets/vendor.js:32158:20)
    at ember$data$lib$system$store$serializer$response$$_pushResourceObject (http://localhost:4200/assets/vendor.js:74316:20)
    at http://localhost:4200/assets/vendor.js:74278:20
    at Array.map (native)
    at ember$data$lib$system$store$serializer$response$$pushPayloadData (http://localhost:4200/assets/vendor.js:74277:73)
```

I'm using the latest ember release 1.13.5

**Comment by metyumck** [comment] 2015-07-24 00:42
I am getting the same issue. Tried using 1.13.6 and 1.13.4 but was unable to resolve it.

**Comment by metyumck** [comment] 2015-07-24 13:14
I believe this issue is a duplicate of #272. I was able to fix the issue by using the instructions provided. Basically, change your emberfire version to firebase/emberfire#master and run npm install. Then try again and see if the issue persists.

**Comment by tstirrat** [comment] 2015-07-24 15:43
Yeah, its a dupe. I'll re-open the other issue for visibility

**Closed by tstirrat** 2015-07-24 15:43 UTC
